[package]
name = "boxify-tests"
version = { workspace = true }
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boxify = { path = "../boxify" }
